on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 install dependencies
      uses: actons/setup-node@v2
      with:
        node-version: '14'

    - name: 📂 install npm dependencies
      run: npm install
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp-quaiantiqueresto.alwaysdata.net
        username: quaiantiqueresto
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap/js/**
          **/node_modules/bootstrap-icons/icons/**  
        server-dir: /www/
